tangem/tangem-sdk-ios

Example/TangemSdkExample/ViewController.swift, TangemSdk/TangemSdk/TangemSdk.swift
Fix displaying Initial message for sign functions
Update example of scan card
=> CSS-137 Initial message fix

Example/TangemSdkExample/AppModel.swift, Example/TangemSdkExample/ContentView.swift, Example/TangemSdkExample/Developer/ResetPinView.swift
Дополнительно поправил иконку, чтобы работало на iOS13 и поставил дефолтную политику - без биометрии
=> IOS-2127 Restore reset pins testing

TangemSdk/TangemSdk/Common/Card/WalletData.swift, TangemSdk/TangemSdk/Common/CardFilter.swift, TangemSdk/TangemSdk/Common/Core/CardSession.swift, TangemSdk/TangemSdk/Common/Deserialization/WalletDataDeserializer.swift, TangemSdk/TangemSdk/Common/Extensions/TangemSdk+Combine.swift, TangemSdk/TangemSdk/Operations/Attestation/VerifyCardRequest.swift, TangemSdk/TangemSdk/Operations/PreflightReadTask.swift, TangemSdk/TangemSdk/TangemSdk.swift
- Ability to pass access code;
- Extend card filter with ranges;
- Fix UI issues;
- Open some structs and interfaces.
=> Add more customisation options and fix bugs.

TangemSdk/TangemSdk/Crypto/Secp256k1Utils.swift
Сделал сумму публичной, чтобы можно было высчитывать UserWalletID для твин карт
=> IOS-2399: Make sum public

TangemSdk/TangemSdk/Common/CardIdFormatter.swift, TangemSdk/TangemSdk/Common/Core/CardSession.swift, TangemSdk/TangemSdk/Common/Core/TangemSdkError.swift, TangemSdk/TangemSdk/Common/Localization/de.lproj/Localizable.strings, TangemSdk/TangemSdk/Common/Localization/en.lproj/Localizable.strings, TangemSdk/TangemSdk/Common/Localization/fr.lproj/Localizable.strings, TangemSdk/TangemSdk/Common/Localization/it.lproj/Localizable.strings, TangemSdk/TangemSdk/Common/Localization/ru.lproj/Localizable.strings, TangemSdk/TangemSdk/Operations/PreflightReadTask.swift, TangemSdk/TangemSdkTests/CommonTests.swift
=> IOS-2410 wrong card wording

TangemSdk/TangemSdk.xcodeproj/project.pbxproj, TangemSdk/TangemSdk/Common/Extensions/LAContext+.swift, TangemSdk/TangemSdk/Common/Services/Secure/BiometricsStorage.swift, TangemSdk/TangemSdk/Common/Services/Secure/BiometricsUtil.swift
Было что-то типа такого после нескольких неуспешных попыток
=> IOS-2547 Hiding "enter password" button in the Face ID prompt

TangemSdk/TangemSdk/Crypto/CryptoUtils.swift
Замапил ошибку на сдкшную, убрал assertions чтобы не мешали дебажным билдам и добавил TODO.
=> IOS-2935 Cover the CryptoKit error

TangemSdk/TangemSdk/Common/Services/Secure/AccessCodeRepository.swift
Если биометрические данные изменились, то коды стираются и мы должны обновить список карт с кодами
=> Updates all the cards after codes fetch

TangemSdk/TangemSdk/Crypto/HDWallet/BIP32/BIP32.swift
Нужно для тестов в блокчейн сдк
=> Make Bip32 public

TangemSdk/TangemSdk/Common/Core/TangemSdkError.swift, TangemSdk/TangemSdk/Operations/Backup/BackupService.swift, TangemSdk/TangemSdk/Operations/Backup/StartBackupCardLinkingTask.swift, TangemSdk/TangemSdk/Operations/Backup/StartPrimaryCardLinkingCommand.swift
Добавил проверку на firmware. Ее можно отключить в рамках skipcompatibilitychecks.
Добавил проверку на keysImportAllowed. Ее нельзя отключить, так как будет ошибка на карте.
=> Add extra backup prechecks

TangemSdk/TangemSdk/UI/Views/Common/ActivityIndicatorView.swift, TangemSdk/TangemSdk/UI/Views/Common/RoundedButtonStyle.swift
=> Resolve ambigious inits

TangemSdk/TangemSdk.xcodeproj/project.pbxproj, TangemSdk/TangemSdk/Common/APDU/Instruction.swift, TangemSdk/TangemSdk/Common/Card/FirmwareVersion.swift, TangemSdk/TangemSdk/Operations/Backup/FinalizePrimaryCardTask.swift, TangemSdk/TangemSdk/Operations/Backup/FinalizeReadBackupDataCommand.swift
Новая команда, которая выполняется при финализации основной карты
=> IOS-3673 Add FinalizeReadBackupDataCommand

TangemSdk/TangemSdk/Crypto/CryptoUtils.swift, TangemSdk/TangemSdk/Crypto/HDWallet/BIP32/BIP32.swift, TangemSdk/TangemSdk/Crypto/Secp256k1Utils.swift
Добавил поддержку импортирования ключей для bip0340
=> Schorr import

TangemSdk/TangemSdk.xcodeproj/project.pbxproj, TangemSdk/TangemSdk/Crypto/Secp256k1Utils.swift, TangemSdk/TangemSdk/Crypto/secp256k1/include/tangem_ecdh.h, TangemSdk/TangemSdk/module.modulemap, TangemSdk/TangemSdkTests/CryptoUtilsTests.swift
Кастомная реализация ECDH отвалилась при обновлении secp256k1
=> Calculate x-only for ECDH

.github/workflows/neutral-build.yml, .github/workflows/tests.yml, TangemSdk/TangemSdk/Common/Core/CardSession.swift, TangemSdk/TangemSdk/Common/Extensions/Publisher+.swift, TangemSdk/TangemSdk/Common/Extensions/TangemSdk+Combine.swift, TangemSdk/TangemSdk/Common/NFC/NFCReader.swift, TangemSdk/TangemSdk/Operations/Attestation/AttestationTask.swift, TangemSdk/TangemSdk/Operations/ResetCode/ResetCodesController.swift
Есть единичный краш за все время, прямо указывающий на unowned.
https://tangem.atlassian.net/browse/IOS-3506
Видимо комбайн все же иногда подглючивает. Решил уж все заменить, тем более тут было просто.
=> Remove all unowned from CardSession

TangemSdk/TangemSdk/Common/Card/FirmwareVersion.swift, TangemSdk/TangemSdkTests/BIP32Tests.swift, TangemSdk/TangemSdkTests/SLIP10Tests.swift
Забыл поднять версию до последней
=> IOS-4136 Bump up to 6.33

TangemSdk/TangemSdk.xcodeproj/project.pbxproj, TangemSdk/TangemSdk/Crypto/BLS/BLSUtils.swift
=> Ios 4286 Implement BLSUtils for BLSSignaturesSwift

TangemSdk/TangemSdk/Operations/Backup/BackupService.swift
Как временное(может и постоянное) решение открываю конфиг, чтобы им манипулировать во время создания бэкапа. Сейчас это нужно для MVP онбординга кольца
=> IOS-4799 Open config for changes

TangemSdk/TangemSdk/Common/JSON/JSONStringConvertible.swift, TangemSdk/TangemSdkTests/JSONRPCTests.swift, TangemSdk/TangemSdkTests/TlvTests.swift
На моем устройстве работает и без фиксов 😃. @megakoko чеки плиз
=> IOS-4927 Try to make tests locale independent

TangemSdk/TangemSdk/Operations/Backup/BackupService.swift
Проблема не воспроизводится, пока добавлю логов. Скорее всего не пишется в кейчейн по какой-то причине
=> IOS-6210 Add backup logs

TangemSdk/TangemSdk/Common/Extensions/TangemSdk+Combine.swift
=> IOS-5193 Refactor extensions

TangemSdk/TangemSdk/Common/Extensions/HexConvertible.swift, TangemSdk/TangemSdk/Crypto/Secp256k1Key.swift, TangemSdk/TangemSdk/Crypto/Secp256k1Signature.swift, TangemSdk/TangemSdk/Crypto/Secp256k1Utils.swift, TangemSdk/TangemSdkTests/CryptoUtilsTests.swift
Понадобилось прокинуть интерфейс для нового метода WalletConnect
=> IOS-6784 Add public key recovery interface

TangemSdk/TangemSdk/Common/Extensions/UIViewController.swift
=> IOS-8114 Fix key window ios15
