TangemSdk/TangemSdk/UI/Views/Common/FloatingTextField.swift
TangemSdk/TangemSdk/UI/Views/Common/FocusableTextField.swift

Поставил в двух местах, чтобы в случае использования компонента отдельно, модификатор не потерялся

IOS-2389 Set default keyboard type

---

TangemSdk/TangemSdk/Common/Extensions/String+.swift
TangemSdk/TangemSdk/Common/Localization/de.lproj/Localizable.strings
TangemSdk/TangemSdk/Common/Localization/en.lproj/Localizable.strings
TangemSdk/TangemSdk/Common/Localization/fr.lproj/Localizable.strings
TangemSdk/TangemSdk/Common/Localization/it.lproj/Localizable.strings
TangemSdk/TangemSdk/Common/Localization/ru.lproj/Localizable.strings
TangemSdk/TangemSdk/Operations/ResetCode/ResetPinService.swift
TangemSdk/TangemSdk/Operations/Sign/SignCommand.swift

Текстовки для сервиса сброса кодов взял из андроида. "Scan the confirmation card" теперь поменялось на "Scan another linked card".
В табличку все добавил.

IOS-2393 Add reset-pin service localisation

---

TangemSdk/TangemSdk/Common/NFC/NFCReader.swift

Есть подозрение на race condition на некоторых минорных версиях иос.  Попробуем такой фикс: перенаправим события со всех подписок в единую очередь.

IOS-2469 Dispatch all events into single queue

---

TangemSdk/TangemSdk/Operations/ResetCode/ResetPinService.swift

Аналогичный фикс помог убрать все плавающие баги в BackupService

IOS-2602 Retain current command explicitly

---

TangemSdk/TangemSdk/Common/NFC/NFCReader.swift

2 секунд иногда становится слишком мало и  при активном SD, следующая команда не успевает отправиться в двухсекундное окно, происходит реконнект к тэгу за пределами 10-сек интервала и вылезает ошибка session invalidated unexpectedly. Увеличил пока idle таймаут в два раза, подумаю как сделать надежнее, опираясь на 10-сек окно реконнекта к тэгу.

IOS-2715 Increase idle timeout

---

TangemSdk/TangemSdk/UI/Views/UserCodes/UserCodeHeaderView.swift

Была такая штука. 
Стало так. На минике не сильно скукоживается.

IOS-2474 Shrinking User Code change header text

---

TangemSdk/TangemSdk/Common/Core/CardSession.swift
TangemSdk/TangemSdk/Operations/Command.swift

Мы не отслеживали ситуацию с прислонением неправильной карты после введения кода (или восстановления кода). Прилетала ошибка инвалид парамс. Я слегка подправил механизм отслеживания текущего тэга, который использовался для проверки карты при реконнектах. Теперь тэг запоминается и держится до тех пор, пока текущая команда не выполнится успешно или не зафейлится окончательно. Если требуется ввести код, то тэг не сбрасывается.

IOS-3108 Do not release a remembered tag until the operation completion

---

TangemSdk/TangemSdk/Operations/ResetCode/ResetPinService.swift

Проблема возникала только при попытке сбросить оба кода низкоуровневого, через example, с отключением хэндлинга ошибок

IOS-3226 Handle both codes resetting

---

TangemSdk/TangemSdk/Common/Core/Config.swift
TangemSdk/TangemSdk/Common/Log/Log.swift

Did set не вызывается при создании, поэтому логгер висел в нерабочем состоянии до первой инициализации сессии. Пофиксил, чтобы было ожидаемое поведение и логгер мог работать сразу.

IOS-3273 Keep the sdk logger configured from start

---

TangemSdk/TangemSdk/UI/TangemSdkStyle.swift
TangemSdk/TangemSdk/UI/Views/Scan/CardView.swift
TangemSdk/TangemSdk/UI/Views/Scan/ReadView.swift

In order to show an image on the scanning screen you need to set the value of the default tag style in TangemSdkStyle to e.g. 
```
.image(uiImage: ..., verticalOffset: 0)
```
- where "uiimage" is the image you want to display, a UIImage built however you like (asset catalog, base64 binary, etc)
- `verticalOffset` is the distance that the image will be shifted vertically from the standard position

IOS-3575 Added a way to show an image in the ReadView

---

TangemSdk/TangemSdk/Common/Core/TangemSdkError.swift
TangemSdk/TangemSdk/Operations/Backup/LinkPrimaryCardCommand.swift
TangemSdk/TangemSdk/Operations/Backup/StartBackupCardLinkingCommand.swift
TangemSdk/TangemSdk/Operations/Backup/WriteBackupDataCommand.swift

Для того, чтобы ограничить сброс конкретной картой в случае этой ошибки

Return cardId inside backupFailedNotEmptyWallets

---

TangemSdk/TangemSdk.xcodeproj/project.pbxproj
TangemSdk/TangemSdk/Common/MasterKeyFactory.swift
TangemSdk/TangemSdk/Common/Services/Secure/GenericPasswordConvertible.swift
TangemSdk/TangemSdk/Crypto/BLS/BLSUtils.swift
TangemSdk/TangemSdk/Crypto/BLS/BigInt.swift
TangemSdk/TangemSdk/Crypto/BLS/HKDFUtil.swift
TangemSdk/TangemSdk/Operations/Wallet/CreateWalletCommand.swift
TangemSdk/TangemSdkTests/BLSTests.swift
TangemSdk/TangemSdkTests/HKDFTests.swift

- Реализовано создание секретного ключа из сида для BLS. Пока в двух вариантах - совместимо с чиа и с актуальным стандартном. По умолчанию совместимость со стандартом, дальше разберемся какой вариант использовать. 
Пришлось реализовать HKDF, потому что в криптокит ее завезли только с иос14. Еще понадобился BigInt, затащил прототип из сортов Свифта, не хочется большие зависимости тянуть. Пришлось доработать стерилизацию в хекс, потому что возвращался строка с нечетным числом символов. (см var hexString: String)
- В CreateWallet теперь пречек на созданный кошелек теперь опциоанльный, потому что для BLS релизовать трудозатратно. Карта все равно не даст записать.
- dataRepresentation не работает для, например SymmetricKey, сделал private, чтобы не выстрелить в ногу.
- добавил тесты для HKDF и …

Impement key import for BLS

---

TangemSdk/TangemSdk/Operations/Sign/SignCommand.swift

Теперь чанк рассчитывается на основе размера пакета.
Примеры 
192 байта - 2 хэша за раз
96 байт - 5 за раз
64 байта - 8 за раз
32 байте - 10 за раз (макс значение)

IOS-3767 Refactor chunking

---

TangemSdk/TangemSdk/Common/NFC/NFCUtils.swift

Проблема подтвердилась и на 15 Pro. Отсюда делаем предположение, что на всех новых девайсах будет новое поведение, поэтому я хардкожу исчерпывающий список устройств со старым поведением. Непонятно куда отнести 14/14 Plus. По анализу разборок вывод сделать не удалось. Решили, что раз обращений не было, не будем на них раскатывать фикс

IOS-5072 Update bad NFC device list

---

TangemSdk/TangemSdk/Crypto/BIP39/EntropyLength.swift

Чтобы в приложении можно было получать количество слов и не проводить расчет слов, а ориентироваться на изначальный источник правды - TangemSDK

IOS-6085: Make EntropyLength words count public

---

TangemSdk/TangemSdk/Operations/Derivation/DeriveWalletPublicKeysTask.swift

Задача - игнорировать ошибки деривации отдельных ключей и не блокировать общий таск

IOS-5986 Skip derivation errors

---

TangemSdk/TangemSdk/Common/Extensions/TangemSdk+Combine.swift

Нужно для рефакторинга сканнера

IOS-5193 Add convenience method

---

TangemSdk/TangemSdk/Common/NFC/NFCReader.swift
TangemSdk/TangemSdk/Common/Network/NetworkService.swift

После ввода access code не сбрасывался alert message на деволтный из-за изменений, привнесенных тут https://github.com/tangem/tangem-sdk-ios/pull/338

IOS-6522 Fix alert message

---

TangemSdk/TangemSdk/Operations/Backup/FinalizeBackupCardTask.swift
TangemSdk/TangemSdk/Operations/Backup/WriteBackupDataCommand.swift

Обновил логику финализации бэкапа на бэкапных картах. Теперь можно будет безопасно продолжать бэкап после прерывания сессии.

IOS-6764 Fix write backup data logic

---

TangemSdk/TangemSdk/Operations/Backup/BackupService.swift

Если прервать финализацию основной карты при копировании, то при дальнейшем восстановлении бэкапа проверялся только факт присутствия данных, без учета количество бэкапных карт. Получалась ситуация, что для одной карты данные были, а для второй - нет. Теперь проверка корректная и позволяет продолжить бэкап с того же места

IOS-6859 Check for cards count

---

TangemSdk/TangemSdk/Common/Card/Card.swift

Нам нужно различать слинкованные карты от бэкапных карт, потому что это влияет на поведение.

IOS-6807 Add backup cards count

---

TangemSdk/TangemSdk/Operations/Backup/BackupService.swift
TangemSdk/TangemSdk/Operations/Backup/StartBackupCardLinkingTask.swift

Нужно возвращать карты в респосах, чтобы грузить по ним картинки во время онбординга

IOS-7652 Return the card in the callback

---

TangemSdk/TangemSdk/Operations/Derivation/DeriveMultipleWalletPublicKeysTask.swift
TangemSdk/TangemSdk/Operations/Derivation/DeriveWalletPublicKeysTask.swift

Для случая большого количества токенов и плохого NFC. Будет возвращаться частичный ответ, что позволит сгенерировать адреса в несколько приседаний

IOS-7043 Return partial response

---

TangemSdk/TangemSdk/Operations/Backup/BackupService.swift
TangemSdk/TangemSdk/Operations/Backup/FinalizePrimaryCardTask.swift

Хэндлинг корнер кейсов
https://tangem.atlassian.net/browse/IOS-7148

IOS-7148 Handle finalized card
